// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: news.proto

package com.itlaoqi.news.proto;

public final class NewProto {
  private NewProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface NewsRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:news.NewsRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string date = 1;</code>
     */
    java.lang.String getDate();
    /**
     * <code>optional string date = 1;</code>
     */
    com.google.protobuf.ByteString
        getDateBytes();
  }
  /**
   * Protobuf type {@code news.NewsRequest}
   */
  public  static final class NewsRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:news.NewsRequest)
      NewsRequestOrBuilder {
    // Use NewsRequest.newBuilder() to construct.
    private NewsRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private NewsRequest() {
      date_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private NewsRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              date_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.itlaoqi.news.proto.NewProto.internal_static_news_NewsRequest_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.itlaoqi.news.proto.NewProto.internal_static_news_NewsRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.itlaoqi.news.proto.NewProto.NewsRequest.class, com.itlaoqi.news.proto.NewProto.NewsRequest.Builder.class);
    }

    public static final int DATE_FIELD_NUMBER = 1;
    private volatile java.lang.Object date_;
    /**
     * <code>optional string date = 1;</code>
     */
    public java.lang.String getDate() {
      java.lang.Object ref = date_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        date_ = s;
        return s;
      }
    }
    /**
     * <code>optional string date = 1;</code>
     */
    public com.google.protobuf.ByteString
        getDateBytes() {
      java.lang.Object ref = date_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        date_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getDateBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, date_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getDateBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, date_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.itlaoqi.news.proto.NewProto.NewsRequest)) {
        return super.equals(obj);
      }
      com.itlaoqi.news.proto.NewProto.NewsRequest other = (com.itlaoqi.news.proto.NewProto.NewsRequest) obj;

      boolean result = true;
      result = result && getDate()
          .equals(other.getDate());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + DATE_FIELD_NUMBER;
      hash = (53 * hash) + getDate().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.itlaoqi.news.proto.NewProto.NewsRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.itlaoqi.news.proto.NewProto.NewsRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.itlaoqi.news.proto.NewProto.NewsRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.itlaoqi.news.proto.NewProto.NewsRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.itlaoqi.news.proto.NewProto.NewsRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.itlaoqi.news.proto.NewProto.NewsRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.itlaoqi.news.proto.NewProto.NewsRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.itlaoqi.news.proto.NewProto.NewsRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.itlaoqi.news.proto.NewProto.NewsRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.itlaoqi.news.proto.NewProto.NewsRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.itlaoqi.news.proto.NewProto.NewsRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code news.NewsRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:news.NewsRequest)
        com.itlaoqi.news.proto.NewProto.NewsRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.itlaoqi.news.proto.NewProto.internal_static_news_NewsRequest_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.itlaoqi.news.proto.NewProto.internal_static_news_NewsRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.itlaoqi.news.proto.NewProto.NewsRequest.class, com.itlaoqi.news.proto.NewProto.NewsRequest.Builder.class);
      }

      // Construct using com.itlaoqi.news.proto.NewProto.NewsRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        date_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.itlaoqi.news.proto.NewProto.internal_static_news_NewsRequest_descriptor;
      }

      public com.itlaoqi.news.proto.NewProto.NewsRequest getDefaultInstanceForType() {
        return com.itlaoqi.news.proto.NewProto.NewsRequest.getDefaultInstance();
      }

      public com.itlaoqi.news.proto.NewProto.NewsRequest build() {
        com.itlaoqi.news.proto.NewProto.NewsRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.itlaoqi.news.proto.NewProto.NewsRequest buildPartial() {
        com.itlaoqi.news.proto.NewProto.NewsRequest result = new com.itlaoqi.news.proto.NewProto.NewsRequest(this);
        result.date_ = date_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.itlaoqi.news.proto.NewProto.NewsRequest) {
          return mergeFrom((com.itlaoqi.news.proto.NewProto.NewsRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.itlaoqi.news.proto.NewProto.NewsRequest other) {
        if (other == com.itlaoqi.news.proto.NewProto.NewsRequest.getDefaultInstance()) return this;
        if (!other.getDate().isEmpty()) {
          date_ = other.date_;
          onChanged();
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.itlaoqi.news.proto.NewProto.NewsRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.itlaoqi.news.proto.NewProto.NewsRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object date_ = "";
      /**
       * <code>optional string date = 1;</code>
       */
      public java.lang.String getDate() {
        java.lang.Object ref = date_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          date_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string date = 1;</code>
       */
      public com.google.protobuf.ByteString
          getDateBytes() {
        java.lang.Object ref = date_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          date_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string date = 1;</code>
       */
      public Builder setDate(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        date_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string date = 1;</code>
       */
      public Builder clearDate() {
        
        date_ = getDefaultInstance().getDate();
        onChanged();
        return this;
      }
      /**
       * <code>optional string date = 1;</code>
       */
      public Builder setDateBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        date_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:news.NewsRequest)
    }

    // @@protoc_insertion_point(class_scope:news.NewsRequest)
    private static final com.itlaoqi.news.proto.NewProto.NewsRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.itlaoqi.news.proto.NewProto.NewsRequest();
    }

    public static com.itlaoqi.news.proto.NewProto.NewsRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<NewsRequest>
        PARSER = new com.google.protobuf.AbstractParser<NewsRequest>() {
      public NewsRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new NewsRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<NewsRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<NewsRequest> getParserForType() {
      return PARSER;
    }

    public com.itlaoqi.news.proto.NewProto.NewsRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface NewsResponeOrBuilder extends
      // @@protoc_insertion_point(interface_extends:news.NewsRespone)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * repeated说明是一个集合（数组），数组每一个元素都是News对象
     * </pre>
     *
     * <code>repeated .news.News news = 1;</code>
     */
    java.util.List<com.itlaoqi.news.proto.NewProto.News> 
        getNewsList();
    /**
     * <pre>
     * repeated说明是一个集合（数组），数组每一个元素都是News对象
     * </pre>
     *
     * <code>repeated .news.News news = 1;</code>
     */
    com.itlaoqi.news.proto.NewProto.News getNews(int index);
    /**
     * <pre>
     * repeated说明是一个集合（数组），数组每一个元素都是News对象
     * </pre>
     *
     * <code>repeated .news.News news = 1;</code>
     */
    int getNewsCount();
    /**
     * <pre>
     * repeated说明是一个集合（数组），数组每一个元素都是News对象
     * </pre>
     *
     * <code>repeated .news.News news = 1;</code>
     */
    java.util.List<? extends com.itlaoqi.news.proto.NewProto.NewsOrBuilder> 
        getNewsOrBuilderList();
    /**
     * <pre>
     * repeated说明是一个集合（数组），数组每一个元素都是News对象
     * </pre>
     *
     * <code>repeated .news.News news = 1;</code>
     */
    com.itlaoqi.news.proto.NewProto.NewsOrBuilder getNewsOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code news.NewsRespone}
   */
  public  static final class NewsRespone extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:news.NewsRespone)
      NewsResponeOrBuilder {
    // Use NewsRespone.newBuilder() to construct.
    private NewsRespone(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private NewsRespone() {
      news_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private NewsRespone(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                news_ = new java.util.ArrayList<com.itlaoqi.news.proto.NewProto.News>();
                mutable_bitField0_ |= 0x00000001;
              }
              news_.add(
                  input.readMessage(com.itlaoqi.news.proto.NewProto.News.parser(), extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          news_ = java.util.Collections.unmodifiableList(news_);
        }
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.itlaoqi.news.proto.NewProto.internal_static_news_NewsRespone_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.itlaoqi.news.proto.NewProto.internal_static_news_NewsRespone_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.itlaoqi.news.proto.NewProto.NewsRespone.class, com.itlaoqi.news.proto.NewProto.NewsRespone.Builder.class);
    }

    public static final int NEWS_FIELD_NUMBER = 1;
    private java.util.List<com.itlaoqi.news.proto.NewProto.News> news_;
    /**
     * <pre>
     * repeated说明是一个集合（数组），数组每一个元素都是News对象
     * </pre>
     *
     * <code>repeated .news.News news = 1;</code>
     */
    public java.util.List<com.itlaoqi.news.proto.NewProto.News> getNewsList() {
      return news_;
    }
    /**
     * <pre>
     * repeated说明是一个集合（数组），数组每一个元素都是News对象
     * </pre>
     *
     * <code>repeated .news.News news = 1;</code>
     */
    public java.util.List<? extends com.itlaoqi.news.proto.NewProto.NewsOrBuilder> 
        getNewsOrBuilderList() {
      return news_;
    }
    /**
     * <pre>
     * repeated说明是一个集合（数组），数组每一个元素都是News对象
     * </pre>
     *
     * <code>repeated .news.News news = 1;</code>
     */
    public int getNewsCount() {
      return news_.size();
    }
    /**
     * <pre>
     * repeated说明是一个集合（数组），数组每一个元素都是News对象
     * </pre>
     *
     * <code>repeated .news.News news = 1;</code>
     */
    public com.itlaoqi.news.proto.NewProto.News getNews(int index) {
      return news_.get(index);
    }
    /**
     * <pre>
     * repeated说明是一个集合（数组），数组每一个元素都是News对象
     * </pre>
     *
     * <code>repeated .news.News news = 1;</code>
     */
    public com.itlaoqi.news.proto.NewProto.NewsOrBuilder getNewsOrBuilder(
        int index) {
      return news_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < news_.size(); i++) {
        output.writeMessage(1, news_.get(i));
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < news_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, news_.get(i));
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.itlaoqi.news.proto.NewProto.NewsRespone)) {
        return super.equals(obj);
      }
      com.itlaoqi.news.proto.NewProto.NewsRespone other = (com.itlaoqi.news.proto.NewProto.NewsRespone) obj;

      boolean result = true;
      result = result && getNewsList()
          .equals(other.getNewsList());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      if (getNewsCount() > 0) {
        hash = (37 * hash) + NEWS_FIELD_NUMBER;
        hash = (53 * hash) + getNewsList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.itlaoqi.news.proto.NewProto.NewsRespone parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.itlaoqi.news.proto.NewProto.NewsRespone parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.itlaoqi.news.proto.NewProto.NewsRespone parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.itlaoqi.news.proto.NewProto.NewsRespone parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.itlaoqi.news.proto.NewProto.NewsRespone parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.itlaoqi.news.proto.NewProto.NewsRespone parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.itlaoqi.news.proto.NewProto.NewsRespone parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.itlaoqi.news.proto.NewProto.NewsRespone parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.itlaoqi.news.proto.NewProto.NewsRespone parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.itlaoqi.news.proto.NewProto.NewsRespone parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.itlaoqi.news.proto.NewProto.NewsRespone prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code news.NewsRespone}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:news.NewsRespone)
        com.itlaoqi.news.proto.NewProto.NewsResponeOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.itlaoqi.news.proto.NewProto.internal_static_news_NewsRespone_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.itlaoqi.news.proto.NewProto.internal_static_news_NewsRespone_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.itlaoqi.news.proto.NewProto.NewsRespone.class, com.itlaoqi.news.proto.NewProto.NewsRespone.Builder.class);
      }

      // Construct using com.itlaoqi.news.proto.NewProto.NewsRespone.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getNewsFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        if (newsBuilder_ == null) {
          news_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          newsBuilder_.clear();
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.itlaoqi.news.proto.NewProto.internal_static_news_NewsRespone_descriptor;
      }

      public com.itlaoqi.news.proto.NewProto.NewsRespone getDefaultInstanceForType() {
        return com.itlaoqi.news.proto.NewProto.NewsRespone.getDefaultInstance();
      }

      public com.itlaoqi.news.proto.NewProto.NewsRespone build() {
        com.itlaoqi.news.proto.NewProto.NewsRespone result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.itlaoqi.news.proto.NewProto.NewsRespone buildPartial() {
        com.itlaoqi.news.proto.NewProto.NewsRespone result = new com.itlaoqi.news.proto.NewProto.NewsRespone(this);
        int from_bitField0_ = bitField0_;
        if (newsBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            news_ = java.util.Collections.unmodifiableList(news_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.news_ = news_;
        } else {
          result.news_ = newsBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.itlaoqi.news.proto.NewProto.NewsRespone) {
          return mergeFrom((com.itlaoqi.news.proto.NewProto.NewsRespone)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.itlaoqi.news.proto.NewProto.NewsRespone other) {
        if (other == com.itlaoqi.news.proto.NewProto.NewsRespone.getDefaultInstance()) return this;
        if (newsBuilder_ == null) {
          if (!other.news_.isEmpty()) {
            if (news_.isEmpty()) {
              news_ = other.news_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureNewsIsMutable();
              news_.addAll(other.news_);
            }
            onChanged();
          }
        } else {
          if (!other.news_.isEmpty()) {
            if (newsBuilder_.isEmpty()) {
              newsBuilder_.dispose();
              newsBuilder_ = null;
              news_ = other.news_;
              bitField0_ = (bitField0_ & ~0x00000001);
              newsBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getNewsFieldBuilder() : null;
            } else {
              newsBuilder_.addAllMessages(other.news_);
            }
          }
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.itlaoqi.news.proto.NewProto.NewsRespone parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.itlaoqi.news.proto.NewProto.NewsRespone) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<com.itlaoqi.news.proto.NewProto.News> news_ =
        java.util.Collections.emptyList();
      private void ensureNewsIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          news_ = new java.util.ArrayList<com.itlaoqi.news.proto.NewProto.News>(news_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.itlaoqi.news.proto.NewProto.News, com.itlaoqi.news.proto.NewProto.News.Builder, com.itlaoqi.news.proto.NewProto.NewsOrBuilder> newsBuilder_;

      /**
       * <pre>
       * repeated说明是一个集合（数组），数组每一个元素都是News对象
       * </pre>
       *
       * <code>repeated .news.News news = 1;</code>
       */
      public java.util.List<com.itlaoqi.news.proto.NewProto.News> getNewsList() {
        if (newsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(news_);
        } else {
          return newsBuilder_.getMessageList();
        }
      }
      /**
       * <pre>
       * repeated说明是一个集合（数组），数组每一个元素都是News对象
       * </pre>
       *
       * <code>repeated .news.News news = 1;</code>
       */
      public int getNewsCount() {
        if (newsBuilder_ == null) {
          return news_.size();
        } else {
          return newsBuilder_.getCount();
        }
      }
      /**
       * <pre>
       * repeated说明是一个集合（数组），数组每一个元素都是News对象
       * </pre>
       *
       * <code>repeated .news.News news = 1;</code>
       */
      public com.itlaoqi.news.proto.NewProto.News getNews(int index) {
        if (newsBuilder_ == null) {
          return news_.get(index);
        } else {
          return newsBuilder_.getMessage(index);
        }
      }
      /**
       * <pre>
       * repeated说明是一个集合（数组），数组每一个元素都是News对象
       * </pre>
       *
       * <code>repeated .news.News news = 1;</code>
       */
      public Builder setNews(
          int index, com.itlaoqi.news.proto.NewProto.News value) {
        if (newsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureNewsIsMutable();
          news_.set(index, value);
          onChanged();
        } else {
          newsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <pre>
       * repeated说明是一个集合（数组），数组每一个元素都是News对象
       * </pre>
       *
       * <code>repeated .news.News news = 1;</code>
       */
      public Builder setNews(
          int index, com.itlaoqi.news.proto.NewProto.News.Builder builderForValue) {
        if (newsBuilder_ == null) {
          ensureNewsIsMutable();
          news_.set(index, builderForValue.build());
          onChanged();
        } else {
          newsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       * repeated说明是一个集合（数组），数组每一个元素都是News对象
       * </pre>
       *
       * <code>repeated .news.News news = 1;</code>
       */
      public Builder addNews(com.itlaoqi.news.proto.NewProto.News value) {
        if (newsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureNewsIsMutable();
          news_.add(value);
          onChanged();
        } else {
          newsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <pre>
       * repeated说明是一个集合（数组），数组每一个元素都是News对象
       * </pre>
       *
       * <code>repeated .news.News news = 1;</code>
       */
      public Builder addNews(
          int index, com.itlaoqi.news.proto.NewProto.News value) {
        if (newsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureNewsIsMutable();
          news_.add(index, value);
          onChanged();
        } else {
          newsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <pre>
       * repeated说明是一个集合（数组），数组每一个元素都是News对象
       * </pre>
       *
       * <code>repeated .news.News news = 1;</code>
       */
      public Builder addNews(
          com.itlaoqi.news.proto.NewProto.News.Builder builderForValue) {
        if (newsBuilder_ == null) {
          ensureNewsIsMutable();
          news_.add(builderForValue.build());
          onChanged();
        } else {
          newsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       * repeated说明是一个集合（数组），数组每一个元素都是News对象
       * </pre>
       *
       * <code>repeated .news.News news = 1;</code>
       */
      public Builder addNews(
          int index, com.itlaoqi.news.proto.NewProto.News.Builder builderForValue) {
        if (newsBuilder_ == null) {
          ensureNewsIsMutable();
          news_.add(index, builderForValue.build());
          onChanged();
        } else {
          newsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       * repeated说明是一个集合（数组），数组每一个元素都是News对象
       * </pre>
       *
       * <code>repeated .news.News news = 1;</code>
       */
      public Builder addAllNews(
          java.lang.Iterable<? extends com.itlaoqi.news.proto.NewProto.News> values) {
        if (newsBuilder_ == null) {
          ensureNewsIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, news_);
          onChanged();
        } else {
          newsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <pre>
       * repeated说明是一个集合（数组），数组每一个元素都是News对象
       * </pre>
       *
       * <code>repeated .news.News news = 1;</code>
       */
      public Builder clearNews() {
        if (newsBuilder_ == null) {
          news_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          newsBuilder_.clear();
        }
        return this;
      }
      /**
       * <pre>
       * repeated说明是一个集合（数组），数组每一个元素都是News对象
       * </pre>
       *
       * <code>repeated .news.News news = 1;</code>
       */
      public Builder removeNews(int index) {
        if (newsBuilder_ == null) {
          ensureNewsIsMutable();
          news_.remove(index);
          onChanged();
        } else {
          newsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <pre>
       * repeated说明是一个集合（数组），数组每一个元素都是News对象
       * </pre>
       *
       * <code>repeated .news.News news = 1;</code>
       */
      public com.itlaoqi.news.proto.NewProto.News.Builder getNewsBuilder(
          int index) {
        return getNewsFieldBuilder().getBuilder(index);
      }
      /**
       * <pre>
       * repeated说明是一个集合（数组），数组每一个元素都是News对象
       * </pre>
       *
       * <code>repeated .news.News news = 1;</code>
       */
      public com.itlaoqi.news.proto.NewProto.NewsOrBuilder getNewsOrBuilder(
          int index) {
        if (newsBuilder_ == null) {
          return news_.get(index);  } else {
          return newsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <pre>
       * repeated说明是一个集合（数组），数组每一个元素都是News对象
       * </pre>
       *
       * <code>repeated .news.News news = 1;</code>
       */
      public java.util.List<? extends com.itlaoqi.news.proto.NewProto.NewsOrBuilder> 
           getNewsOrBuilderList() {
        if (newsBuilder_ != null) {
          return newsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(news_);
        }
      }
      /**
       * <pre>
       * repeated说明是一个集合（数组），数组每一个元素都是News对象
       * </pre>
       *
       * <code>repeated .news.News news = 1;</code>
       */
      public com.itlaoqi.news.proto.NewProto.News.Builder addNewsBuilder() {
        return getNewsFieldBuilder().addBuilder(
            com.itlaoqi.news.proto.NewProto.News.getDefaultInstance());
      }
      /**
       * <pre>
       * repeated说明是一个集合（数组），数组每一个元素都是News对象
       * </pre>
       *
       * <code>repeated .news.News news = 1;</code>
       */
      public com.itlaoqi.news.proto.NewProto.News.Builder addNewsBuilder(
          int index) {
        return getNewsFieldBuilder().addBuilder(
            index, com.itlaoqi.news.proto.NewProto.News.getDefaultInstance());
      }
      /**
       * <pre>
       * repeated说明是一个集合（数组），数组每一个元素都是News对象
       * </pre>
       *
       * <code>repeated .news.News news = 1;</code>
       */
      public java.util.List<com.itlaoqi.news.proto.NewProto.News.Builder> 
           getNewsBuilderList() {
        return getNewsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.itlaoqi.news.proto.NewProto.News, com.itlaoqi.news.proto.NewProto.News.Builder, com.itlaoqi.news.proto.NewProto.NewsOrBuilder> 
          getNewsFieldBuilder() {
        if (newsBuilder_ == null) {
          newsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              com.itlaoqi.news.proto.NewProto.News, com.itlaoqi.news.proto.NewProto.News.Builder, com.itlaoqi.news.proto.NewProto.NewsOrBuilder>(
                  news_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          news_ = null;
        }
        return newsBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:news.NewsRespone)
    }

    // @@protoc_insertion_point(class_scope:news.NewsRespone)
    private static final com.itlaoqi.news.proto.NewProto.NewsRespone DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.itlaoqi.news.proto.NewProto.NewsRespone();
    }

    public static com.itlaoqi.news.proto.NewProto.NewsRespone getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<NewsRespone>
        PARSER = new com.google.protobuf.AbstractParser<NewsRespone>() {
      public NewsRespone parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new NewsRespone(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<NewsRespone> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<NewsRespone> getParserForType() {
      return PARSER;
    }

    public com.itlaoqi.news.proto.NewProto.NewsRespone getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface NewsOrBuilder extends
      // @@protoc_insertion_point(interface_extends:news.News)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional int32 id = 1;</code>
     */
    int getId();

    /**
     * <code>optional string title = 2;</code>
     */
    java.lang.String getTitle();
    /**
     * <code>optional string title = 2;</code>
     */
    com.google.protobuf.ByteString
        getTitleBytes();

    /**
     * <code>optional int64 createTime = 4;</code>
     */
    long getCreateTime();
  }
  /**
   * <pre>
   * News新闻实体对象
   * </pre>
   *
   * Protobuf type {@code news.News}
   */
  public  static final class News extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:news.News)
      NewsOrBuilder {
    // Use News.newBuilder() to construct.
    private News(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private News() {
      id_ = 0;
      title_ = "";
      createTime_ = 0L;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private News(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              id_ = input.readInt32();
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              title_ = s;
              break;
            }
            case 32: {

              createTime_ = input.readInt64();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.itlaoqi.news.proto.NewProto.internal_static_news_News_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.itlaoqi.news.proto.NewProto.internal_static_news_News_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.itlaoqi.news.proto.NewProto.News.class, com.itlaoqi.news.proto.NewProto.News.Builder.class);
    }

    public static final int ID_FIELD_NUMBER = 1;
    private int id_;
    /**
     * <code>optional int32 id = 1;</code>
     */
    public int getId() {
      return id_;
    }

    public static final int TITLE_FIELD_NUMBER = 2;
    private volatile java.lang.Object title_;
    /**
     * <code>optional string title = 2;</code>
     */
    public java.lang.String getTitle() {
      java.lang.Object ref = title_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        title_ = s;
        return s;
      }
    }
    /**
     * <code>optional string title = 2;</code>
     */
    public com.google.protobuf.ByteString
        getTitleBytes() {
      java.lang.Object ref = title_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        title_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CREATETIME_FIELD_NUMBER = 4;
    private long createTime_;
    /**
     * <code>optional int64 createTime = 4;</code>
     */
    public long getCreateTime() {
      return createTime_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (id_ != 0) {
        output.writeInt32(1, id_);
      }
      if (!getTitleBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, title_);
      }
      if (createTime_ != 0L) {
        output.writeInt64(4, createTime_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (id_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, id_);
      }
      if (!getTitleBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, title_);
      }
      if (createTime_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(4, createTime_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.itlaoqi.news.proto.NewProto.News)) {
        return super.equals(obj);
      }
      com.itlaoqi.news.proto.NewProto.News other = (com.itlaoqi.news.proto.NewProto.News) obj;

      boolean result = true;
      result = result && (getId()
          == other.getId());
      result = result && getTitle()
          .equals(other.getTitle());
      result = result && (getCreateTime()
          == other.getCreateTime());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId();
      hash = (37 * hash) + TITLE_FIELD_NUMBER;
      hash = (53 * hash) + getTitle().hashCode();
      hash = (37 * hash) + CREATETIME_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getCreateTime());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.itlaoqi.news.proto.NewProto.News parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.itlaoqi.news.proto.NewProto.News parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.itlaoqi.news.proto.NewProto.News parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.itlaoqi.news.proto.NewProto.News parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.itlaoqi.news.proto.NewProto.News parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.itlaoqi.news.proto.NewProto.News parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.itlaoqi.news.proto.NewProto.News parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.itlaoqi.news.proto.NewProto.News parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.itlaoqi.news.proto.NewProto.News parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.itlaoqi.news.proto.NewProto.News parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.itlaoqi.news.proto.NewProto.News prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * News新闻实体对象
     * </pre>
     *
     * Protobuf type {@code news.News}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:news.News)
        com.itlaoqi.news.proto.NewProto.NewsOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.itlaoqi.news.proto.NewProto.internal_static_news_News_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.itlaoqi.news.proto.NewProto.internal_static_news_News_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.itlaoqi.news.proto.NewProto.News.class, com.itlaoqi.news.proto.NewProto.News.Builder.class);
      }

      // Construct using com.itlaoqi.news.proto.NewProto.News.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        id_ = 0;

        title_ = "";

        createTime_ = 0L;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.itlaoqi.news.proto.NewProto.internal_static_news_News_descriptor;
      }

      public com.itlaoqi.news.proto.NewProto.News getDefaultInstanceForType() {
        return com.itlaoqi.news.proto.NewProto.News.getDefaultInstance();
      }

      public com.itlaoqi.news.proto.NewProto.News build() {
        com.itlaoqi.news.proto.NewProto.News result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.itlaoqi.news.proto.NewProto.News buildPartial() {
        com.itlaoqi.news.proto.NewProto.News result = new com.itlaoqi.news.proto.NewProto.News(this);
        result.id_ = id_;
        result.title_ = title_;
        result.createTime_ = createTime_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.itlaoqi.news.proto.NewProto.News) {
          return mergeFrom((com.itlaoqi.news.proto.NewProto.News)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.itlaoqi.news.proto.NewProto.News other) {
        if (other == com.itlaoqi.news.proto.NewProto.News.getDefaultInstance()) return this;
        if (other.getId() != 0) {
          setId(other.getId());
        }
        if (!other.getTitle().isEmpty()) {
          title_ = other.title_;
          onChanged();
        }
        if (other.getCreateTime() != 0L) {
          setCreateTime(other.getCreateTime());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.itlaoqi.news.proto.NewProto.News parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.itlaoqi.news.proto.NewProto.News) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int id_ ;
      /**
       * <code>optional int32 id = 1;</code>
       */
      public int getId() {
        return id_;
      }
      /**
       * <code>optional int32 id = 1;</code>
       */
      public Builder setId(int value) {
        
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 id = 1;</code>
       */
      public Builder clearId() {
        
        id_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object title_ = "";
      /**
       * <code>optional string title = 2;</code>
       */
      public java.lang.String getTitle() {
        java.lang.Object ref = title_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          title_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string title = 2;</code>
       */
      public com.google.protobuf.ByteString
          getTitleBytes() {
        java.lang.Object ref = title_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          title_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string title = 2;</code>
       */
      public Builder setTitle(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        title_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string title = 2;</code>
       */
      public Builder clearTitle() {
        
        title_ = getDefaultInstance().getTitle();
        onChanged();
        return this;
      }
      /**
       * <code>optional string title = 2;</code>
       */
      public Builder setTitleBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        title_ = value;
        onChanged();
        return this;
      }

      private long createTime_ ;
      /**
       * <code>optional int64 createTime = 4;</code>
       */
      public long getCreateTime() {
        return createTime_;
      }
      /**
       * <code>optional int64 createTime = 4;</code>
       */
      public Builder setCreateTime(long value) {
        
        createTime_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 createTime = 4;</code>
       */
      public Builder clearCreateTime() {
        
        createTime_ = 0L;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:news.News)
    }

    // @@protoc_insertion_point(class_scope:news.News)
    private static final com.itlaoqi.news.proto.NewProto.News DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.itlaoqi.news.proto.NewProto.News();
    }

    public static com.itlaoqi.news.proto.NewProto.News getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<News>
        PARSER = new com.google.protobuf.AbstractParser<News>() {
      public News parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new News(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<News> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<News> getParserForType() {
      return PARSER;
    }

    public com.itlaoqi.news.proto.NewProto.News getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_news_NewsRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_news_NewsRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_news_NewsRespone_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_news_NewsRespone_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_news_News_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_news_News_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\nnews.proto\022\004news\"\033\n\013NewsRequest\022\014\n\004dat" +
      "e\030\001 \001(\t\"\'\n\013NewsRespone\022\030\n\004news\030\001 \003(\0132\n.n" +
      "ews.News\"5\n\004News\022\n\n\002id\030\001 \001(\005\022\r\n\005title\030\002 " +
      "\001(\t\022\022\n\ncreateTime\030\004 \001(\0032=\n\013NewsService\022." +
      "\n\004list\022\021.news.NewsRequest\032\021.news.NewsRes" +
      "pone\"\000B$\n\026com.itlaoqi.news.protoB\010NewPro" +
      "toP\000b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_news_NewsRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_news_NewsRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_news_NewsRequest_descriptor,
        new java.lang.String[] { "Date", });
    internal_static_news_NewsRespone_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_news_NewsRespone_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_news_NewsRespone_descriptor,
        new java.lang.String[] { "News", });
    internal_static_news_News_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_news_News_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_news_News_descriptor,
        new java.lang.String[] { "Id", "Title", "CreateTime", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
